import { createContext } from "react";

export const AppContext = createContext({
  isLoggedIn: false,
  setIsLoggedIn: (value) => {},
  setAccessToken: (value) => {},
  setRefreshToken: (value) => {},
  setUserData: (value) => {},
  userData: {},
  accessToken: "",
  refreshToken: "",
  loading: false,
  setLoading: (value) => {},
  logout: () => {},
  isOnLandingPage: true,
  setIsOnLandingPage: (val) => {},
  isSignupOpen: false,
  setIsSignupOpen: (val) => {},
  loginTime: "",
  setLoginTime: (val) => {},
  availableChats: "",
  setAvailableChats: (val) => {},
  crowdAudio: null,
  setCrowdAudio: (value) => {},
  crowdWinAudio: null,
  setCrowdWinAudio: (val) => {},
  inBetweenAudio: null,
  setCrowdInBetweenAudio: (val) => {},
  isBgWhite: false,
  setIsBgWhite: (val) => {},
  openCoinsModal: false,
  setOpenCoinsModal: (val) => {},
  openWallet: false,
  setOpenWallet: (val) => {},
});

export const HomeContext = createContext({
  messageData: {},
  setMessageData: (value) => {},
  playerBalance: null,
  gameId: null,
  setGameId: (value) => {},
  coinClient: null,
  setCoinClient: (value) => {},
  isPlayingHiLo: false,
  setIsPlayingHiLo: (val) => {},
  gameClient: null,
  setGameClient: (val) => {},
  isHiLoOpen: false,
  setIsHiLoOpen: (val) => {},
  hiLoDefaultCreditPurchase: 10,
  setHiLoDefaultCreditPurchase: (val) => {},
  isPurchaseCardsOpen: false,
  setIsPurchaseCardsOpen: (val) => {},
  purchaseCardDefaultCredit: 5,
  setPurchaseCardDefaultCredit: (val) => {},
});

export const HiLoContext = createContext({
  amount: 1,
  updateAmount: (val) => {},
  isPlaying: false,
  setIsPlaying: (val) => {},
  play: () => {},
  selected: "none",
  select: (val) => {},
});

//contexts for bingo90
export const Bingo90Context = createContext({
  messageData: {},
  setMessageData: (value) => {},
  playerBalance: null,
  gameId: null,
  setGameId: (value) => {},
  coinClient: null,
  setCoinClient: (value) => {},
  isPlayingHiLo: false,
  setIsPlayingHiLo: (val) => {},
  gameClient: null,
  setGameClient: (val) => {},
  isHiLoOpen: false,
  setIsHiLoOpen: (val) => {},
  hiLoDefaultCreditPurchase: 10,
  setHiLoDefaultCreditPurchase: (val) => {},
  isPurchaseCardsOpen: false,
  setIsPurchaseCardsOpen: (val) => {},
  purchaseCardDefaultCredit: 5,
  setPurchaseCardDefaultCredit: (val) => {},
  luckyNumbers: null,
  setLuckyNumbers: (val) => {},
  currentWinner: null,
  setCurrentWinner: (val) => {},

  jackpotPrize: null,
  setJackpotPrize: (val) => {},
  bingoPrize: null,
  setBingoPrize: (val) => {},
  twoLinePrize: null,
  setTwoLinePrize: (val) => {},
  linePrize: null,
  setLinePrize: (val) => {},
  isMiddleBarButtonsVisible: null,
  setIsMiddleBarButtonsVisible: (val) => {},
  viewMode: null,
  setViewMode: (val) => {},
  isBuyClicked: null,
  setIsBuyClicked: (val) => {},
  isWinningNow: null,
  setIsWinnigNow: (val) => {},
  clickedIndexies: null,
  setClickedIndexies: (val) => {},
  isNewGame: null,
  setIsNewGame: (val) => {},
  totalBet: null,
  setTotalBet: (val) => {},
  isBettedHilo: null,
  setIsBettedHilo: (val) => {},
  luckyBetOpen: null,
  isLuckyBetOpen: (val) => {},
  isWon: null,
  setIsWon: (val) => {},
  previousBalance: null,
  setPreviousBalance: (val) => {},
  chipsAmount: null,
  setChipsAmount: (val) => {},
  matrixTickets: null,
  setMatrixTickets: (val) => {},
  isTicketsStyleNormal: null,
  setIsTicketsStyleNormal : (val) => {},
  luckySent: null,
  setLuckySent : (val) => {},
  luckyInfoDialogOpen: null,
  setLuckyInfoDialogOpen: (val) => {},
  luckyDialogOpen: null,
  setLuckyDialogOpen: (val) => {},
  signedNumbers: null,
  setSignedNumbers: (val) => {},
  playingNow: null,
  setPlayingNow: (val) => {},
});
